name: CI

on:
  - push
  - pull_request

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pnpm install

      - name: Validate content
        run: pnpm content-collections build
